import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Home from "@/components/landingpage/Home";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <Home />
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
